require 'specinfra/backend/base'
require 'specinfra/backend/exec'
require 'specinfra/backend/ssh'
require 'specinfra/backend/powershell/script_helper'
require 'specinfra/backend/powershell/command'
require 'specinfra/backend/cmd'
require 'specinfra/backend/winrm'
require 'specinfra/backend/shellscript'
